predownload packages

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -41,16 +41,29 @@ remove_dir () {
 }
 
 download () {
-
-	DOWNLOAD_PATH=$PACKAGES;
+	DOWNLOAD_PATH=$PACKAGES
 		
 	if [ ! -z "$3" ]; then
 		mkdir -p $PACKAGES/$3
 		DOWNLOAD_PATH=$PACKAGES/$3
-	fi;
+	fi
+
+	dirname="$DOWNLOAD_PATH/$2"
+	case $dirname in
+		*.tar)
+			dirname=$(basename $dirname .tar);;
+		*.tar.bz2)
+			dirname=$(basename $dirname .tar.bz2);;
+		*.tar.gz)
+			dirname=$(basename $dirname .tar.gz);;
+		*.tgz)
+			dirname=$(basename $dirname .tgz);;
+		*)
+			dirname=$(basename $dirname);;
+	esac
+	echo "extract path ==> $DOWNLOAD_PATH/$dirname"
 
 	if [ ! -f "$DOWNLOAD_PATH/$2" ]; then
-
 		echo "Downloading $1"
 		curl -L --silent -o "$DOWNLOAD_PATH/$2" "$1"
 
@@ -75,7 +88,13 @@ download () {
 			echo "Failed to extract $2";
 			exit 1
 		fi
-
+	else
+		if [ ! -d "$DOWNLOAD_PATH/$dirname" ]; then 
+			if ! tar -xvf "$DOWNLOAD_PATH/$2" -C "$DOWNLOAD_PATH" 2>/dev/null >/dev/null; then
+				echo "Failed to extract $2";
+				exit 1
+			fi
+		fi	
 	fi
 }
 
@@ -175,7 +194,7 @@ if build "yasm"; then
 fi
 
 if build "nasm"; then
-	download "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.gz" "nasm.tar.gz"
+	download "http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.gz" "nasm-2.13.03.tar.gz"
 	cd $PACKAGES/nasm-2.13.03 || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
 	execute make -j $MJOBS
@@ -186,7 +205,7 @@ fi
 if build "opencore"; then
 	download "http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.5.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencore-amr%2Ffiles%2Fopencore-amr%2F&ts=1442256558&use_mirror=netassist" "opencore-amr-0.1.5.tar.gz"
 	cd $PACKAGES/opencore-amr-0.1.5 || exit
-	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
+	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static CFLAGS="-fPIC" CXXFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "opencore"
@@ -194,7 +213,7 @@ fi
 
 if build "libvpx"; then
     download "https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz" "libvpx-1.7.0.tar.gz"
-    cd $PACKAGES/libvpx-*0 || exit
+    cd $PACKAGES/libvpx-1.7.0 || exit
 
     if [[ "$OSTYPE" == "darwin"* ]]; then
         echo "Applying Darwin patch"
@@ -211,14 +230,14 @@ fi
 if build "lame"; then
 	download "http://kent.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz" "lame-3.100.tar.gz"
 	cd $PACKAGES/lame-3.100 || exit
-	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
+	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static CFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "lame"
 fi
 
 if build "xvidcore"; then
-	download "http://downloads.xvid.org/downloads/xvidcore-1.3.4.tar.gz" "xvidcore-1.3.4.tar.gz"
+	download "http://downloads.xvid.org/downloads/xvidcore-1.3.4.tar.gz" "xvidcore.tar.gz"
 	cd $PACKAGES/xvidcore  || exit
 	cd build/generic  || exit
 	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
@@ -233,11 +252,11 @@ if build "xvidcore"; then
 fi
 
 if build "x264"; then
-	download "http://ftp.videolan.org/pub/x264/snapshots/x264-snapshot-20190204-2245-stable.tar.bz2" "last_x264.tar.bz2"
-	cd $PACKAGES/x264-snapshot-* || exit
+	download "http://ftp.videolan.org/pub/x264/snapshots/x264-snapshot-20190204-2245-stable.tar.bz2" "x264-snapshot-20190204-2245-stable.tar.bz2"
+	cd $PACKAGES/x264-snapshot-20190204-2245-stable || exit
 
 	if [[ "$OSTYPE" == "linux-gnu" ]]; then
-		execute ./configure --prefix=${WORKSPACE} --enable-static --enable-pic CXXFLAGS="-fPIC"
+		execute ./configure --prefix=${WORKSPACE} --enable-static --enable-pic
     else
         execute ./configure --prefix=${WORKSPACE} --enable-static --enable-pic
     fi
@@ -251,7 +270,7 @@ fi
 if build "libogg"; then
 	download "http://downloads.xiph.org/releases/ogg/libogg-1.3.3.tar.gz" "libogg-1.3.3.tar.gz"
 	cd $PACKAGES/libogg-1.3.3 || exit
-	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
+	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static CFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "libogg"
@@ -260,19 +279,22 @@ fi
 if build "libvorbis"; then
 	download "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz" "libvorbis-1.3.6.tar.gz"
 	cd $PACKAGES/libvorbis-1.3.6 || exit
-	execute ./configure --prefix=${WORKSPACE} --with-ogg-libraries=${WORKSPACE}/lib --with-ogg-includes=${WORKSPACE}/include/ --enable-static --disable-shared --disable-oggtest
+	execute ./configure --prefix=${WORKSPACE} --with-ogg-libraries=${WORKSPACE}/lib --with-ogg-includes=${WORKSPACE}/include/ \
+		--enable-static --disable-shared --disable-oggtest CFLAGS="-fPIC" CXXFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "libvorbis"
 fi
 
 if build "libtheora"; then
-	download "http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz" "libtheora-1.1.1.tar.bz"
+	download "http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.gz" "libtheora-1.1.1.tar.gz"
 	cd $PACKAGES/libtheora-1.1.1 || exit
 	sed "s/-fforce-addr//g" configure > configure.patched
 	chmod +x configure.patched
 	mv configure.patched configure
-	execute ./configure --prefix=${WORKSPACE} --with-ogg-libraries=${WORKSPACE}/lib --with-ogg-includes=${WORKSPACE}/include/ --with-vorbis-libraries=${WORKSPACE}/lib --with-vorbis-includes=${WORKSPACE}/include/ --enable-static --disable-shared --disable-oggtest --disable-vorbistest --disable-examples --disable-asm
+	execute ./configure --prefix=${WORKSPACE} --with-ogg-libraries=${WORKSPACE}/lib --with-ogg-includes=${WORKSPACE}/include/ \
+		--with-vorbis-libraries=${WORKSPACE}/lib --with-vorbis-includes=${WORKSPACE}/include/ \
+		--enable-static --disable-shared --disable-oggtest --disable-vorbistest --disable-examples --disable-asm CFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "libtheora"
@@ -287,21 +309,21 @@ if build "pkg-config"; then
 	build_done "pkg-config"
 fi
 
-if build "cmake"; then
-	download "https://cmake.org/files/v3.11/cmake-3.11.3.tar.gz" "cmake-3.11.3.tar.gz"
-	cd $PACKAGES/cmake-3.11.3  || exit
-	rm Modules/FindJava.cmake
-	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt
-	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt
-	execute ./configure --prefix=${WORKSPACE}
-	execute make -j $MJOBS
-	execute make install
-	build_done "cmake"
-fi
+# if build "cmake"; then
+# 	download "https://cmake.org/files/v3.11/cmake-3.11.3.tar.gz" "cmake-3.11.3.tar.gz"
+# 	cd $PACKAGES/cmake-3.11.3  || exit
+# 	rm Modules/FindJava.cmake
+# 	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt
+# 	perl -p -i -e "s/get_filename_component.JNIPATH/#get_filename_component(JNIPATH/g" Tests/CMakeLists.txt
+# 	execute ./configure --prefix=${WORKSPACE}
+# 	execute make -j $MJOBS
+# 	execute make install
+# 	build_done "cmake"
+# fi
 
 if build "vid_stab"; then
-	download "https://codeload.github.com/georgmartius/vid.stab/legacy.tar.gz/release-0.98b" "vid.stab-0.98b-transcode-1.1-binary-x86_64.tgz"
-	cd $PACKAGES/georgmartius-vid* || exit
+	download "https://codeload.github.com/georgmartius/vid.stab/legacy.tar.gz/release-0.98b" "georgmartius-vid.stab-3b35b4d.tgz"
+	cd $PACKAGES/georgmartius-vid.stab-3b35b4d || exit
 	perl -p -i -e "s/vidstab SHARED/vidstab STATIC/" CMakeLists.txt
 	execute cmake -DCMAKE_INSTALL_PREFIX:PATH=${WORKSPACE} .
 	execute make install
@@ -309,8 +331,8 @@ if build "vid_stab"; then
 fi
 
 if build "x265"; then
-	download "https://bitbucket.org/multicoreware/x265/downloads/x265_3.0.tar.gz" "x265-3.0.tar.gz"
-	cd $PACKAGES/x265_* || exit
+	download "https://bitbucket.org/multicoreware/x265/downloads/x265_3.0.tar.gz" "x265_3.0.tar.gz"
+	cd $PACKAGES/x265_3.0 || exit
 	cd source || exit
 	execute cmake -DCMAKE_INSTALL_PREFIX:PATH=${WORKSPACE} -DENABLE_SHARED:bool=off .
 	execute make -j $MJOBS
@@ -323,14 +345,14 @@ fi
 if build "fdk_aac"; then
 	download "http://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.6.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencore-amr%2Ffiles%2Ffdk-aac%2F&ts=1457561564&use_mirror=kent" "fdk-aac-0.1.6.tar.gz"
 	cd $PACKAGES/fdk-aac-0.1.6 || exit
-	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static
+	execute ./configure --prefix=${WORKSPACE} --disable-shared --enable-static CFLAGS="-fPIC" CXXFLAGS="-fPIC"
 	execute make -j $MJOBS
 	execute make install
 	build_done "fdk_aac"
 fi
 
 if build "av1"; then
-	download "https://aomedia.googlesource.com/aom/+archive/52ea88fd18719bac1acfa6847f834ae6d2ae136f.tar.gz" "av1.tar.gz" "av1"
+	download "https://aomedia.googlesource.com/aom/+archive/52ea88fd18719bac1acfa6847f834ae6d2ae136f.tar.gz" "aom-52ea88fd18719bac1acfa6847f834ae6d2ae136f.tar.gz" "av1"
 	cd $PACKAGES/av1 || exit
 	mkdir -p $PACKAGES/aom_build
 	cd $PACKAGES/aom_build
@@ -342,7 +364,7 @@ fi
 
 
 build "ffmpeg"
-download "http://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2" "ffmpeg-snapshot.tar.bz2"
+download "http://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2" "ffmpeg-4.1.tar.bz2"
 cd $PACKAGES/ffmpeg-4.1 || exit
 ./configure $ADDITIONAL_CONFIGURE_OPTIONS \
     --pkgconfigdir="$WORKSPACE/lib/pkgconfig" \
